[package]
name = "formiga-tools"
default-run = "formiga-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
epaint.workspace = true
serde.workspace = true
formiga-art = { path = "../formiga-art" }
formiga-core = { path = "../formiga-core" }
formiga-home-contract = { path = "../formiga-home-contract" }
formiga-travel = { path = "../formiga-travel" }
gif.workspace = true
png.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
